<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PricesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('prices')->delete();
        
        \DB::table('prices')->insert(array (
            0 => 
            array (
                'created_at' => '2023-02-22 19:34:00',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 1,
                'plan_id' => 1,
                'price' => 99.0,
                'priceable_id' => 1,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Plan',
                'slug' => 'plan_subscription',
                'subscription_id' => NULL,
                'updated_at' => '2024-07-16 15:10:41',
            ),
            1 => 
            array (
                'created_at' => '2023-02-22 19:34:00',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 2,
                'plan_id' => 1,
                'price' => 26.0,
                'priceable_id' => 1,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Plan',
                'slug' => 'delivery',
                'subscription_id' => NULL,
                'updated_at' => '2023-09-04 21:46:20',
            ),
            2 => 
            array (
                'created_at' => '2023-02-22 19:34:00',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 3,
                'plan_id' => NULL,
                'price' => 29.0,
                'priceable_id' => NULL,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Plan',
                'slug' => 'delivery',
                'subscription_id' => NULL,
                'updated_at' => '2023-09-04 21:46:20',
            ),
            3 => 
            array (
                'created_at' => '2023-03-02 14:24:00',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 18,
                'plan_id' => NULL,
                'price' => 0.0,
                'priceable_id' => NULL,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Plan',
                'slug' => 'plan_subscription',
                'subscription_id' => NULL,
                'updated_at' => '2024-07-16 15:10:41',
            ),
            4 => 
            array (
                'created_at' => '2023-08-13 21:55:59',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 2907,
                'plan_id' => NULL,
                'price' => 25.0,
                'priceable_id' => 1971,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Product',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2023-08-13 21:55:59',
            ),
            5 => 
            array (
                'created_at' => '2023-11-13 18:59:58',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 7614,
                'plan_id' => NULL,
                'price' => 0.0,
                'priceable_id' => 3,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Plan',
                'slug' => 'plan_subscription',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            6 => 
            array (
                'created_at' => '2023-11-13 18:59:58',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 7615,
                'plan_id' => NULL,
                'price' => 39.0,
                'priceable_id' => 4,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Plan',
                'slug' => 'plan_subscription',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            7 => 
            array (
                'created_at' => '2023-11-13 18:59:58',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 7616,
                'plan_id' => NULL,
                'price' => 129.0,
                'priceable_id' => 5,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Plan',
                'slug' => 'plan_subscription',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            8 => 
            array (
                'created_at' => '2024-01-23 08:31:08',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 14680,
                'plan_id' => NULL,
                'price' => 15.0,
                'priceable_id' => 3880,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Product',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-01-23 08:31:08',
            ),
            9 => 
            array (
                'created_at' => '2024-04-21 18:02:32',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 29249,
                'plan_id' => NULL,
                'price' => 33.0,
                'priceable_id' => 7306,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Product',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-04-21 18:31:35',
            ),
            10 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31183,
                'plan_id' => 4,
                'price' => 29.0,
                'priceable_id' => 4,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Plan',
                'slug' => 'integration',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            11 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31184,
                'plan_id' => 4,
                'price' => 29.0,
                'priceable_id' => 4,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Plan',
                'slug' => 'member',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            12 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31185,
                'plan_id' => 5,
                'price' => 0.0,
                'priceable_id' => 5,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Plan',
                'slug' => 'integration',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            13 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31186,
                'plan_id' => 5,
                'price' => 19.0,
                'priceable_id' => 5,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Plan',
                'slug' => 'member',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            14 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31187,
                'plan_id' => 5,
                'price' => 99.0,
                'priceable_id' => 5,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Plan',
                'slug' => 'address',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            15 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31188,
                'plan_id' => 3,
                'price' => 35.0,
                'priceable_id' => 1,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            16 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31189,
                'plan_id' => 4,
                'price' => 32.0,
                'priceable_id' => 1,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            17 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31190,
                'plan_id' => 4,
                'price' => 99.0,
                'priceable_id' => 1,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'shield',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            18 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31191,
                'plan_id' => 5,
                'price' => 31.0,
                'priceable_id' => 1,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            19 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31192,
                'plan_id' => 5,
                'price' => 249.0,
                'priceable_id' => 1,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'shield',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            20 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31193,
                'plan_id' => 3,
                'price' => 35.0,
                'priceable_id' => 2,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            21 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31194,
                'plan_id' => 4,
                'price' => 32.0,
                'priceable_id' => 2,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            22 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31195,
                'plan_id' => 4,
                'price' => 99.0,
                'priceable_id' => 2,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'shield',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            23 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31196,
                'plan_id' => 5,
                'price' => 31.0,
                'priceable_id' => 2,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            24 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31197,
                'plan_id' => 5,
                'price' => 249.0,
                'priceable_id' => 2,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'shield',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            25 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31198,
                'plan_id' => 3,
                'price' => 15.0,
                'priceable_id' => 3,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'margin',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            26 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31199,
                'plan_id' => 4,
                'price' => 7.5,
                'priceable_id' => 3,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'margin',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            27 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31200,
                'plan_id' => 4,
                'price' => 99.0,
                'priceable_id' => 3,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'shield',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            28 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31201,
                'plan_id' => 5,
                'price' => 5.0,
                'priceable_id' => 3,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'margin',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            29 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31202,
                'plan_id' => 5,
                'price' => 249.0,
                'priceable_id' => 3,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'shield',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            30 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31203,
                'plan_id' => 4,
                'price' => 35.0,
                'priceable_id' => 4,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            31 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31204,
                'plan_id' => 4,
                'price' => 99.0,
                'priceable_id' => 4,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'shield',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            32 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => '{"prices": {"total_deliveries_count": {"50": 33, "100": 29, "200": 28, "300": 26}}}',
                'id' => 31205,
                'plan_id' => 5,
                'price' => 34.0,
                'priceable_id' => 4,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'modular',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            33 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31206,
                'plan_id' => 5,
                'price' => 249.0,
                'priceable_id' => 4,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'shield',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            34 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31207,
                'plan_id' => 4,
                'price' => 35.0,
                'priceable_id' => 5,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            35 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31208,
                'plan_id' => 4,
                'price' => 99.0,
                'priceable_id' => 5,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'shield',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            36 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => '{"prices": {"total_deliveries_count": {"50": 33, "100": 29, "200": 28, "300": 26}}}',
                'id' => 31209,
                'plan_id' => 5,
                'price' => 34.0,
                'priceable_id' => 5,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'modular',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            37 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31210,
                'plan_id' => 5,
                'price' => 249.0,
                'priceable_id' => 5,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'shield',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            38 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31211,
                'plan_id' => 5,
                'price' => 0.0,
                'priceable_id' => 7,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            39 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31212,
                'plan_id' => 5,
                'price' => 249.0,
                'priceable_id' => 7,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'shield',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            40 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31213,
                'plan_id' => 3,
                'price' => 50.0,
                'priceable_id' => 8,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'margin',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            41 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31214,
                'plan_id' => 4,
                'price' => 35.0,
                'priceable_id' => 8,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'margin',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            42 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31215,
                'plan_id' => 5,
                'price' => 15.0,
                'priceable_id' => 8,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'margin',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            43 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31216,
                'plan_id' => 5,
                'price' => 360.0,
                'priceable_id' => 8,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'shield',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            44 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31217,
                'plan_id' => 3,
                'price' => 0.0,
                'priceable_id' => 9,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            45 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31218,
                'plan_id' => 4,
                'price' => 0.0,
                'priceable_id' => 9,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            46 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31219,
                'plan_id' => 4,
                'price' => 99.0,
                'priceable_id' => 9,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'shield',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            47 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31220,
                'plan_id' => 5,
                'price' => 0.0,
                'priceable_id' => 9,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            48 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31221,
                'plan_id' => 5,
                'price' => 249.0,
                'priceable_id' => 9,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'shield',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            49 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31222,
                'plan_id' => 4,
                'price' => 70.0,
                'priceable_id' => 10,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            50 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31223,
                'plan_id' => 4,
                'price' => 99.0,
                'priceable_id' => 10,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'shield',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            51 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => '{"prices": {"total_deliveries_count": {"50": 49.5, "100": 43.5, "200": 42, "300": 39}}}',
                'id' => 31224,
                'plan_id' => 5,
                'price' => 51.0,
                'priceable_id' => 10,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'modular',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            52 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31225,
                'plan_id' => 5,
                'price' => 249.0,
                'priceable_id' => 10,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'shield',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            53 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31226,
                'plan_id' => 3,
                'price' => 25.0,
                'priceable_id' => 11,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            54 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31227,
                'plan_id' => 4,
                'price' => 22.0,
                'priceable_id' => 11,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            55 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31228,
                'plan_id' => 4,
                'price' => 99.0,
                'priceable_id' => 11,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'shield',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            56 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31229,
                'plan_id' => 5,
                'price' => 20.0,
                'priceable_id' => 11,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            57 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31230,
                'plan_id' => 5,
                'price' => 249.0,
                'priceable_id' => 11,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'shield',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            58 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31231,
                'plan_id' => 3,
                'price' => 35.0,
                'priceable_id' => 56,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Polygon',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            59 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31232,
                'plan_id' => 4,
                'price' => 34.0,
                'priceable_id' => 56,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Polygon',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            60 => 
            array (
                'created_at' => '2024-08-01 01:47:38',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31233,
                'plan_id' => 5,
                'price' => 33.0,
                'priceable_id' => 56,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Polygon',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-08-01 01:47:38',
            ),
            61 => 
            array (
                'created_at' => '2024-08-08 21:23:48',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31409,
                'plan_id' => 3,
                'price' => 50.0,
                'priceable_id' => 12,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'margin',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-08 21:23:48',
            ),
            62 => 
            array (
                'created_at' => '2024-08-08 21:23:48',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31410,
                'plan_id' => 4,
                'price' => 35.0,
                'priceable_id' => 12,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'margin',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-08 21:23:48',
            ),
            63 => 
            array (
                'created_at' => '2024-08-08 21:23:48',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31411,
                'plan_id' => 5,
                'price' => 15.0,
                'priceable_id' => 12,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'margin',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-08 21:23:48',
            ),
            64 => 
            array (
                'created_at' => '2024-08-08 21:23:48',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31412,
                'plan_id' => 5,
                'price' => 360.0,
                'priceable_id' => 12,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\ShippingCode',
                'slug' => 'shield',
                'subscription_id' => NULL,
                'updated_at' => '2024-08-08 21:23:48',
            ),
            65 => 
            array (
                'created_at' => '2024-09-02 01:07:43',
                'currency_id' => 2,
                'data' => '{"condition": {"courier_status": {"CANCELED": 0}}}',
                'id' => 31771,
                'plan_id' => NULL,
                'price' => 25.0,
                'priceable_id' => 10,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Courier',
                'slug' => 'cost',
                'subscription_id' => NULL,
                'updated_at' => '2024-09-02 01:07:43',
            ),
            66 => 
            array (
                'created_at' => '2024-09-02 01:07:43',
                'currency_id' => 2,
                'data' => '{"condition": {"courier_status": {"RETURNED": 50, "CANCELED_BY_COURIER_ON_PICKUP": 17.5}}}',
                'id' => 31772,
                'plan_id' => NULL,
                'price' => 25.0,
                'priceable_id' => 12,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Courier',
                'slug' => 'cost',
                'subscription_id' => NULL,
                'updated_at' => '2024-09-02 01:07:43',
            ),
            67 => 
            array (
                'created_at' => '2024-09-02 01:07:43',
                'currency_id' => 2,
                'data' => '{"condition": {"status": {"cancelled": 0, "service_cancel": 0}}}',
                'id' => 31773,
                'plan_id' => NULL,
                'price' => 25.0,
                'priceable_id' => 14,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Courier',
                'slug' => 'cost',
                'subscription_id' => NULL,
                'updated_at' => '2024-09-02 01:07:43',
            ),
            68 => 
            array (
                'created_at' => '2024-09-02 01:07:43',
                'currency_id' => 2,
                'data' => '{"condition": {"status": {"cancelled": 0, "service_cancel": 0}}}',
                'id' => 31774,
                'plan_id' => NULL,
                'price' => 37.5,
                'priceable_id' => 52,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Polygon',
                'slug' => 'cost',
                'subscription_id' => NULL,
                'updated_at' => '2024-09-02 01:07:43',
            ),
            69 => 
            array (
                'created_at' => '2024-09-02 01:07:43',
                'currency_id' => 2,
                'data' => '{"condition": {"status": {"cancelled": 0, "service_cancel": 0}}}',
                'id' => 31775,
                'plan_id' => NULL,
                'price' => 37.5,
                'priceable_id' => 55,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Polygon',
                'slug' => 'cost',
                'subscription_id' => NULL,
                'updated_at' => '2024-09-02 01:07:43',
            ),
            70 => 
            array (
                'created_at' => '2024-09-02 01:07:43',
                'currency_id' => 2,
                'data' => '{"condition": {"courier_status": {"12": 30}}}',
                'id' => 31776,
                'plan_id' => NULL,
                'price' => 15.0,
                'priceable_id' => 4,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Courier',
                'slug' => 'cost',
                'subscription_id' => NULL,
                'updated_at' => '2024-09-02 01:07:43',
            ),
            71 => 
            array (
                'created_at' => '2024-09-02 12:29:56',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31780,
                'plan_id' => NULL,
                'price' => 30.0,
                'priceable_id' => 42,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Polygon',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-09-02 12:29:56',
            ),
            72 => 
            array (
                'created_at' => '2024-09-02 12:30:04',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 31781,
                'plan_id' => NULL,
                'price' => 30.0,
                'priceable_id' => 40,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Polygon',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-09-02 12:30:04',
            ),
            73 => 
            array (
                'created_at' => '2024-10-20 17:38:00',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 32494,
                'plan_id' => NULL,
                'price' => 18.0,
                'priceable_id' => 10477,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Product',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-10-20 17:38:00',
            ),
            74 => 
            array (
                'created_at' => '2024-10-20 19:24:08',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 32496,
                'plan_id' => NULL,
                'price' => 16.0,
                'priceable_id' => 10479,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Product',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-10-20 19:24:08',
            ),
            75 => 
            array (
                'created_at' => '2024-10-22 17:57:07',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 32515,
                'plan_id' => NULL,
                'price' => 29.0,
                'priceable_id' => 58,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Polygon',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-10-22 17:57:07',
            ),
            76 => 
            array (
                'created_at' => '2024-10-22 17:57:07',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 32516,
                'plan_id' => NULL,
                'price' => 25.0,
                'priceable_id' => 58,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Polygon',
                'slug' => 'cost',
                'subscription_id' => NULL,
                'updated_at' => '2024-10-22 17:57:07',
            ),
            77 => 
            array (
                'created_at' => '2024-10-27 15:29:27',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 32568,
                'plan_id' => NULL,
                'price' => 18.0,
                'priceable_id' => 10549,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Product',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-10-27 15:29:27',
            ),
            78 => 
            array (
                'created_at' => '2024-10-28 16:45:10',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 32594,
                'plan_id' => NULL,
                'price' => 555.0,
                'priceable_id' => 1,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Product',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-10-28 16:45:10',
            ),
            79 => 
            array (
                'created_at' => '2024-10-28 16:45:11',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 32595,
                'plan_id' => NULL,
                'price' => 17.25,
                'priceable_id' => 2,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Product',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-10-28 16:45:11',
            ),
            80 => 
            array (
                'created_at' => '2024-10-28 16:45:11',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 32596,
                'plan_id' => NULL,
                'price' => 50.0,
                'priceable_id' => 15,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Product',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-10-28 16:45:11',
            ),
            81 => 
            array (
                'created_at' => '2024-10-28 16:45:11',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 32597,
                'plan_id' => NULL,
                'price' => 1.0,
                'priceable_id' => 18,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Product',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-10-28 16:45:11',
            ),
            82 => 
            array (
                'created_at' => '2024-10-28 16:45:11',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 32598,
                'plan_id' => NULL,
                'price' => 2388.0,
                'priceable_id' => 21,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Product',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-10-28 16:45:11',
            ),
            83 => 
            array (
                'created_at' => '2024-10-28 16:45:11',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 32599,
                'plan_id' => NULL,
                'price' => 100.0,
                'priceable_id' => 27,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Product',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-10-28 16:45:11',
            ),
            84 => 
            array (
                'created_at' => '2024-10-28 16:45:11',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 32600,
                'plan_id' => NULL,
                'price' => 233.0,
                'priceable_id' => 29,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Product',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-10-28 16:45:11',
            ),
            85 => 
            array (
                'created_at' => '2024-10-28 16:45:11',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 32601,
                'plan_id' => NULL,
                'price' => 89.99,
                'priceable_id' => 37,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Product',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-10-28 16:45:11',
            ),
            86 => 
            array (
                'created_at' => '2024-10-28 16:45:11',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 32602,
                'plan_id' => NULL,
                'price' => 399.99,
                'priceable_id' => 38,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Product',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-10-28 16:45:11',
            ),
            87 => 
            array (
                'created_at' => '2024-10-28 16:45:11',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 32603,
                'plan_id' => NULL,
                'price' => 1000.0,
                'priceable_id' => 43,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Product',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-10-28 16:45:11',
            ),
            88 => 
            array (
                'created_at' => '2024-10-28 16:45:11',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 32604,
                'plan_id' => NULL,
                'price' => 50.0,
                'priceable_id' => 117,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Product',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-10-28 16:45:11',
            ),
            89 => 
            array (
                'created_at' => '2024-10-28 16:45:11',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 32605,
                'plan_id' => NULL,
                'price' => 13.0,
                'priceable_id' => 2058,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Product',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-10-28 16:45:11',
            ),
            90 => 
            array (
                'created_at' => '2024-10-28 16:45:11',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 32606,
                'plan_id' => NULL,
                'price' => 18.0,
                'priceable_id' => 2059,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Product',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-10-28 16:45:11',
            ),
            91 => 
            array (
                'created_at' => '2024-10-28 16:45:11',
                'currency_id' => 2,
                'data' => NULL,
                'id' => 32607,
                'plan_id' => NULL,
                'price' => 10.0,
                'priceable_id' => 2060,
                'priceable_slug' => NULL,
                'priceable_type' => 'App\\Models\\Product',
                'slug' => NULL,
                'subscription_id' => NULL,
                'updated_at' => '2024-10-28 16:45:11',
            ),
        ));
        
        
    }
}