<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ShippingCodesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('shipping_codes')->delete();
        
        \DB::table('shipping_codes')->insert(array (
            0 => 
            array (
                'code' => 'VELOAPPIO_SAME_DAY',
                'created_at' => '2023-02-22 19:34:00',
                'dropoff_max_days' => 1,
                'id' => 1,
                'initial_free_km' => NULL,
                'is_international' => 0,
                'is_on_demand' => 0,
                'is_replacement' => 0,
                'is_return' => 0,
                'is_same_day' => 1,
                'max_dimensions' => '[40, 40, 40]',
                'max_weight' => 10.0,
                'min_dimensions' => NULL,
                'min_monthly_deliveries' => NULL,
                'min_weight' => NULL,
                'pickup_max_days' => NULL,
                'updated_at' => '2024-01-01 21:27:00',
            ),
            1 => 
            array (
                'code' => 'VELOAPPIO_NEXT_DAY',
                'created_at' => '2023-02-22 19:34:13',
                'dropoff_max_days' => 2,
                'id' => 2,
                'initial_free_km' => NULL,
                'is_international' => 0,
                'is_on_demand' => 0,
                'is_replacement' => 0,
                'is_return' => 0,
                'is_same_day' => 0,
                'max_dimensions' => '[40, 40, 40]',
                'max_weight' => 10.0,
                'min_dimensions' => NULL,
                'min_monthly_deliveries' => NULL,
                'min_weight' => NULL,
                'pickup_max_days' => NULL,
                'updated_at' => '2024-01-01 21:27:00',
            ),
            2 => 
            array (
                'code' => 'VELOAPPIO_ON_DEMAND',
                'created_at' => '2023-02-22 19:34:00',
                'dropoff_max_days' => 1,
                'id' => 3,
                'initial_free_km' => 2.0,
                'is_international' => 0,
                'is_on_demand' => 1,
                'is_replacement' => 0,
                'is_return' => 0,
                'is_same_day' => 0,
                'max_dimensions' => '[40, 40, 40]',
                'max_weight' => 10.0,
                'min_dimensions' => NULL,
                'min_monthly_deliveries' => NULL,
                'min_weight' => NULL,
                'pickup_max_days' => NULL,
                'updated_at' => '2024-01-01 21:27:00',
            ),
            3 => 
            array (
                'code' => 'VELOAPPIO_STANDARD',
                'created_at' => '2023-03-23 20:19:58',
                'dropoff_max_days' => 3,
                'id' => 4,
                'initial_free_km' => NULL,
                'is_international' => 0,
                'is_on_demand' => 0,
                'is_replacement' => 0,
                'is_return' => 0,
                'is_same_day' => 0,
                'max_dimensions' => '[40, 40, 40]',
                'max_weight' => 10.0,
                'min_dimensions' => NULL,
                'min_monthly_deliveries' => NULL,
                'min_weight' => NULL,
                'pickup_max_days' => NULL,
                'updated_at' => '2024-01-01 21:27:00',
            ),
            4 => 
            array (
                'code' => 'VELOAPPIO_RETURN',
                'created_at' => '2023-05-29 00:29:57',
                'dropoff_max_days' => 5,
                'id' => 5,
                'initial_free_km' => NULL,
                'is_international' => 0,
                'is_on_demand' => 0,
                'is_replacement' => 0,
                'is_return' => 1,
                'is_same_day' => 0,
                'max_dimensions' => '[40, 40, 40]',
                'max_weight' => 10.0,
                'min_dimensions' => NULL,
                'min_monthly_deliveries' => NULL,
                'min_weight' => NULL,
                'pickup_max_days' => NULL,
                'updated_at' => '2024-01-01 21:27:00',
            ),
            5 => 
            array (
                'code' => 'VELOAPPIO_LOCKER',
                'created_at' => '2023-06-20 01:58:16',
                'dropoff_max_days' => NULL,
                'id' => 6,
                'initial_free_km' => NULL,
                'is_international' => 0,
                'is_on_demand' => 0,
                'is_replacement' => 0,
                'is_return' => 0,
                'is_same_day' => 0,
                'max_dimensions' => '[40, 40, 40]',
                'max_weight' => 10.0,
                'min_dimensions' => NULL,
                'min_monthly_deliveries' => NULL,
                'min_weight' => NULL,
                'pickup_max_days' => NULL,
                'updated_at' => '2023-06-20 01:58:16',
            ),
            6 => 
            array (
                'code' => 'VELOAPPIO_B2B',
                'created_at' => '2023-06-20 01:58:16',
                'dropoff_max_days' => NULL,
                'id' => 7,
                'initial_free_km' => NULL,
                'is_international' => 0,
                'is_on_demand' => 0,
                'is_replacement' => 0,
                'is_return' => 0,
                'is_same_day' => 0,
                'max_dimensions' => '[100, 100, 100]',
                'max_weight' => 100.0,
                'min_dimensions' => NULL,
                'min_monthly_deliveries' => NULL,
                'min_weight' => 10.0,
                'pickup_max_days' => NULL,
                'updated_at' => '2023-06-22 00:32:48',
            ),
            7 => 
            array (
                'code' => 'VELOAPPIO_INTERNATIONAL',
                'created_at' => '2023-09-04 21:48:33',
                'dropoff_max_days' => NULL,
                'id' => 8,
                'initial_free_km' => NULL,
                'is_international' => 1,
                'is_on_demand' => 0,
                'is_replacement' => 0,
                'is_return' => 0,
                'is_same_day' => 0,
                'max_dimensions' => NULL,
                'max_weight' => NULL,
                'min_dimensions' => NULL,
                'min_monthly_deliveries' => NULL,
                'min_weight' => NULL,
                'pickup_max_days' => NULL,
                'updated_at' => '2023-09-04 21:48:33',
            ),
            8 => 
            array (
                'code' => 'VELOAPPIO_DOMESTIC',
                'created_at' => '2023-09-11 20:59:57',
                'dropoff_max_days' => NULL,
                'id' => 9,
                'initial_free_km' => NULL,
                'is_international' => 0,
                'is_on_demand' => 0,
                'is_replacement' => 0,
                'is_return' => 0,
                'is_same_day' => 0,
                'max_dimensions' => NULL,
                'max_weight' => NULL,
                'min_dimensions' => NULL,
                'min_monthly_deliveries' => NULL,
                'min_weight' => NULL,
                'pickup_max_days' => NULL,
                'updated_at' => '2023-09-11 20:59:57',
            ),
            9 => 
            array (
                'code' => 'VELOAPPIO_REPLACEMENT',
                'created_at' => '2023-11-13 18:59:58',
                'dropoff_max_days' => 5,
                'id' => 10,
                'initial_free_km' => NULL,
                'is_international' => 0,
                'is_on_demand' => 0,
                'is_replacement' => 1,
                'is_return' => 0,
                'is_same_day' => 0,
                'max_dimensions' => '[40, 40, 40]',
                'max_weight' => 10.0,
                'min_dimensions' => NULL,
                'min_monthly_deliveries' => NULL,
                'min_weight' => NULL,
                'pickup_max_days' => NULL,
                'updated_at' => '2024-01-01 21:27:00',
            ),
            10 => 
            array (
                'code' => 'VELOAPPIO_LOCKER2LOCKER',
                'created_at' => '2024-03-17 19:22:11',
                'dropoff_max_days' => NULL,
                'id' => 11,
                'initial_free_km' => NULL,
                'is_international' => 0,
                'is_on_demand' => 0,
                'is_replacement' => 0,
                'is_return' => 0,
                'is_same_day' => 0,
                'max_dimensions' => NULL,
                'max_weight' => NULL,
                'min_dimensions' => NULL,
                'min_monthly_deliveries' => NULL,
                'min_weight' => NULL,
                'pickup_max_days' => NULL,
                'updated_at' => '2024-03-17 19:22:11',
            ),
            11 => 
            array (
                'code' => 'VELOAPPIO_INTERNATIONAL_RETURN',
                'created_at' => '2024-08-08 21:23:48',
                'dropoff_max_days' => NULL,
                'id' => 12,
                'initial_free_km' => NULL,
                'is_international' => 1,
                'is_on_demand' => 0,
                'is_replacement' => 0,
                'is_return' => 1,
                'is_same_day' => 0,
                'max_dimensions' => NULL,
                'max_weight' => NULL,
                'min_dimensions' => NULL,
                'min_monthly_deliveries' => NULL,
                'min_weight' => NULL,
                'pickup_max_days' => NULL,
                'updated_at' => '2024-08-08 21:23:48',
            ),
        ));
        
        
    }
}