<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StoresTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('stores')->delete();
        
        \DB::table('stores')->insert(array (
            0 => 
            array (
                'always_show_next_day_options' => 1,
                'billing_limit' => NULL,
                'blocked_at' => NULL,
                'blocked_by' => NULL,
                'courier_id' => NULL,
                'created_at' => '2023-02-22 19:34:00',
                'currency_id' => 2,
                'deleted_at' => NULL,
                'enterprise_billing' => 1,
                'first_name' => 'Itay',
                'id' => 1,
                'imperial_units' => 0,
                'last_name' => 'Rijensky',
                'name' => 'Velo',
                'phone' => '0545445412',
                'pricing_settings' => '[{"threshold": "0", "VELOAPPIO_DOMESTIC": {"price": "5", "active": "", "margin": "1"}, "VELOAPPIO_NEXT_DAY": {"price": "32", "active": "1"}, "VELOAPPIO_SAME_DAY": {"price": "33", "active": "1"}, "VELOAPPIO_STANDARD": {"price": "34", "active": ""}, "VELOAPPIO_ON_DEMAND": {"price": "5", "active": "", "margin": "1"}, "VELOAPPIO_INTERNATIONAL": {"price": "5", "active": "", "margin": "1"}, "VELOAPPIO_LOCKER2LOCKER": {"price": "21", "active": "1"}}, {"threshold": "60", "VELOAPPIO_DOMESTIC": {"price": "5", "active": "", "margin": "1"}, "VELOAPPIO_NEXT_DAY": {"price": "2", "active": "1"}, "VELOAPPIO_SAME_DAY": {"price": "3", "active": "1"}, "VELOAPPIO_STANDARD": {"price": "1", "active": ""}, "VELOAPPIO_ON_DEMAND": {"price": "5", "active": "", "margin": "1"}, "VELOAPPIO_INTERNATIONAL": {"price": "5", "active": "", "margin": "1"}, "VELOAPPIO_LOCKER2LOCKER": {"price": "0.5", "active": "1"}}]',
                'slug' => 'velo',
                'suspended' => 0,
                'tax_id' => '45454545',
                'timezone' => 'Asia/Jerusalem',
                'updated_at' => '2024-09-16 00:07:54',
                'user_id' => 1,
                'validate_inventory' => 0,
                'validate_weight' => 0,
                'volume' => 200,
                'website' => 'https://veloapp.io',
                'week_starts_at' => 7,
                'weekly_deliveries_schedule' => '{"1": {"hours": "12:30", "active": true}, "2": {"hours": "12:30", "active": true}, "3": {"hours": "12:30", "active": true}, "4": {"hours": "12:30", "active": true}, "5": {"hours": "12:30", "active": true}, "6": {"hours": "00:00", "active": false}, "7": {"hours": "12:30", "active": true}}',
            ),
            1 => 
            array (
                'always_show_next_day_options' => 1,
                'billing_limit' => NULL,
                'blocked_at' => NULL,
                'blocked_by' => NULL,
                'courier_id' => NULL,
                'created_at' => '2023-05-02 11:48:08',
                'currency_id' => 2,
                'deleted_at' => NULL,
                'enterprise_billing' => 0,
                'first_name' => 'Ari',
                'id' => 16,
                'imperial_units' => 0,
                'last_name' => 'Efron',
                'name' => 'Ari',
                'phone' => '0543095056',
                'pricing_settings' => '[{"threshold": "0", "VELOAPPIO_DOMESTIC": {"price": "5", "active": "", "margin": "1"}, "VELOAPPIO_NEXT_DAY": {"price": "30", "active": "1"}, "VELOAPPIO_SAME_DAY": {"price": "30", "active": "1"}, "VELOAPPIO_STANDARD": {"price": "30", "active": "1"}, "VELOAPPIO_ON_DEMAND": {"price": "5", "active": "", "margin": "1"}, "VELOAPPIO_INTERNATIONAL": {"price": "5", "active": "", "margin": "1"}, "VELOAPPIO_LOCKER2LOCKER": {"price": "20", "active": ""}}]',
                'slug' => 'ari',
                'suspended' => 0,
                'tax_id' => '214846004',
                'timezone' => 'Asia/Jerusalem',
                'updated_at' => '2024-09-02 00:44:02',
                'user_id' => 28,
                'validate_inventory' => 0,
                'validate_weight' => 0,
                'volume' => 240,
                'website' => 'https://velomarketing.io',
                'week_starts_at' => 1,
                'weekly_deliveries_schedule' => '{"1": {"hours": "12:30", "active": true}, "2": {"hours": "12:30", "active": true}, "3": {"hours": "12:30", "active": true}, "4": {"hours": "12:30", "active": true}, "5": {"hours": "12:30", "active": true}, "6": {"hours": "12:30", "active": true}, "7": {"hours": "12:30", "active": true}}',
            ),
            2 => 
            array (
                'always_show_next_day_options' => 1,
                'billing_limit' => NULL,
                'blocked_at' => NULL,
                'blocked_by' => NULL,
                'courier_id' => NULL,
                'created_at' => '2023-05-16 12:34:04',
                'currency_id' => 1,
                'deleted_at' => NULL,
                'enterprise_billing' => 0,
                'first_name' => 'fuck',
                'id' => 26,
                'imperial_units' => 0,
                'last_name' => 'mylife',
                'name' => 'fmlStore',
                'phone' => '7323369206',
                'pricing_settings' => '[{"threshold": "0", "VELOAPPIO_DOMESTIC": {"price": "5", "active": "", "margin": "1"}, "VELOAPPIO_NEXT_DAY": {"price": "30", "active": "1"}, "VELOAPPIO_SAME_DAY": {"price": "30", "active": "1"}, "VELOAPPIO_STANDARD": {"price": "30", "active": "1"}, "VELOAPPIO_ON_DEMAND": {"price": "10", "active": "1", "margin": "1"}, "VELOAPPIO_INTERNATIONAL": {"price": "5", "active": "", "margin": "1"}, "VELOAPPIO_LOCKER2LOCKER": {"price": "20", "active": ""}}]',
                'slug' => 'fmlstore',
                'suspended' => 0,
                'tax_id' => NULL,
                'timezone' => 'Asia/Jerusalem',
                'updated_at' => '2024-03-20 01:40:43',
                'user_id' => 1,
                'validate_inventory' => 0,
                'validate_weight' => 0,
                'volume' => 0,
                'website' => 'https://fmlstore.com',
                'week_starts_at' => 1,
                'weekly_deliveries_schedule' => '{"1": {"hours": "12:30", "active": true}, "2": {"hours": "12:30", "active": true}, "3": {"hours": "12:30", "active": true}, "4": {"hours": "12:30", "active": true}, "5": {"hours": "12:30", "active": true}, "6": {"hours": "12:30", "active": true}, "7": {"hours": "12:30", "active": true}}',
            ),
            3 => 
            array (
                'always_show_next_day_options' => 1,
                'billing_limit' => NULL,
                'blocked_at' => NULL,
                'blocked_by' => NULL,
                'courier_id' => NULL,
                'created_at' => '2023-07-13 14:19:43',
                'currency_id' => 2,
                'deleted_at' => NULL,
                'enterprise_billing' => 0,
                'first_name' => 'velo',
                'id' => 94,
                'imperial_units' => 0,
                'last_name' => 'test',
                'name' => 'velotest1',
                'phone' => '054111111',
                'pricing_settings' => '[{"threshold": "100", "VELOAPPIO_DOMESTIC": {"price": 5, "active": false, "margin": true}, "VELOAPPIO_NEXT_DAY": {"price": "200", "active": true}, "VELOAPPIO_SAME_DAY": {"price": "250", "active": true}, "VELOAPPIO_STANDARD": {"price": "300", "active": true}, "VELOAPPIO_ON_DEMAND": {"price": 5, "active": false, "margin": true}, "VELOAPPIO_INTERNATIONAL": {"price": 5, "active": false, "margin": true}, "VELOAPPIO_LOCKER2LOCKER": {"price": "20", "active": false}}]',
                'slug' => 'velotest',
                'suspended' => 0,
                'tax_id' => NULL,
                'timezone' => 'Asia/Jerusalem',
                'updated_at' => '2024-06-20 18:00:01',
                'user_id' => 484,
                'validate_inventory' => 0,
                'validate_weight' => 0,
                'volume' => 0,
                'website' => 'https://veloapp.io/',
                'week_starts_at' => 7,
                'weekly_deliveries_schedule' => '{"1": {"hours": "12:30", "active": true}, "2": {"hours": "12:30", "active": true}, "3": {"hours": "12:30", "active": true}, "4": {"hours": "12:30", "active": true}, "5": {"hours": "12:30", "active": false}, "6": {"hours": "12:30", "active": false}, "7": {"hours": "12:30", "active": true}}',
            ),
            4 => 
            array (
                'always_show_next_day_options' => 1,
                'billing_limit' => NULL,
                'blocked_at' => NULL,
                'blocked_by' => NULL,
                'courier_id' => NULL,
                'created_at' => '2023-07-17 19:36:54',
                'currency_id' => 2,
                'deleted_at' => NULL,
                'enterprise_billing' => 0,
                'first_name' => 'Nachshon',
                'id' => 110,
                'imperial_units' => 0,
                'last_name' => 'Hertz',
                'name' => 'Nachshon',
                'phone' => '972528310508',
                'pricing_settings' => '[{"threshold": 0, "VELOAPPIO_DOMESTIC": {"price": 5, "active": false, "margin": true}, "VELOAPPIO_NEXT_DAY": {"price": 30, "active": true}, "VELOAPPIO_SAME_DAY": {"price": 30, "active": true}, "VELOAPPIO_STANDARD": {"price": 30, "active": true}, "VELOAPPIO_ON_DEMAND": {"price": 5, "active": false, "margin": true}, "VELOAPPIO_INTERNATIONAL": {"price": 5, "active": false, "margin": true}, "VELOAPPIO_LOCKER2LOCKER": {"price": "20", "active": false}}]',
                'slug' => 'nachshon',
                'suspended' => 0,
                'tax_id' => NULL,
                'timezone' => 'Asia/Jerusalem',
                'updated_at' => '2024-06-20 18:00:01',
                'user_id' => 127,
                'validate_inventory' => 0,
                'validate_weight' => 0,
                'volume' => 0,
                'website' => 'https://nachshon.com',
                'week_starts_at' => 1,
                'weekly_deliveries_schedule' => '{"1": {"hours": "12:30", "active": true}, "2": {"hours": "12:30", "active": true}, "3": {"hours": "12:30", "active": true}, "4": {"hours": "12:30", "active": true}, "5": {"hours": "12:30", "active": true}, "6": {"hours": "12:30", "active": true}, "7": {"hours": "12:30", "active": true}}',
            ),
            5 => 
            array (
                'always_show_next_day_options' => 1,
                'billing_limit' => NULL,
                'blocked_at' => NULL,
                'blocked_by' => NULL,
                'courier_id' => NULL,
                'created_at' => '2023-08-01 07:09:27',
                'currency_id' => 1,
                'deleted_at' => NULL,
                'enterprise_billing' => 0,
                'first_name' => 'Amit',
                'id' => 127,
                'imperial_units' => 1,
                'last_name' => 'Bazak',
                'name' => 'LIAGE',
                'phone' => '7323369206',
                'pricing_settings' => '[{"threshold": "0", "VELOAPPIO_DOMESTIC": {"price": 5, "active": false, "margin": true}, "VELOAPPIO_NEXT_DAY": {"price": "30", "active": true}, "VELOAPPIO_SAME_DAY": {"price": "30", "active": true}, "VELOAPPIO_STANDARD": {"price": "30", "active": true}, "VELOAPPIO_ON_DEMAND": {"price": 5, "active": false, "margin": true}, "VELOAPPIO_INTERNATIONAL": {"price": 5, "active": false, "margin": true}, "VELOAPPIO_LOCKER2LOCKER": {"price": "20", "active": false}}]',
                'slug' => 'liage',
                'suspended' => 1,
                'tax_id' => '4243242',
                'timezone' => 'Asia/Jerusalem',
                'updated_at' => '2024-10-27 11:48:55',
                'user_id' => 146,
                'validate_inventory' => 0,
                'validate_weight' => 0,
                'volume' => 80,
                'website' => 'https://LIAGEBEAUTY.COM',
                'week_starts_at' => 1,
                'weekly_deliveries_schedule' => '{"1": {"hours": "12:30", "active": true}, "2": {"hours": "12:30", "active": true}, "3": {"hours": "12:30", "active": true}, "4": {"hours": "12:30", "active": true}, "5": {"hours": "12:30", "active": true}, "6": {"hours": "12:30", "active": true}, "7": {"hours": "12:30", "active": true}}',
            ),
            6 => 
            array (
                'always_show_next_day_options' => 1,
                'billing_limit' => NULL,
                'blocked_at' => NULL,
                'blocked_by' => NULL,
                'courier_id' => NULL,
                'created_at' => '2023-08-14 21:37:04',
                'currency_id' => 2,
                'deleted_at' => NULL,
                'enterprise_billing' => 0,
                'first_name' => 'tzah',
                'id' => 160,
                'imperial_units' => 0,
                'last_name' => 'bakal',
                'name' => 'tzah',
                'phone' => '0528212178',
                'pricing_settings' => '[{"threshold": 0, "VELOAPPIO_DOMESTIC": {"price": 5, "active": false, "margin": true}, "VELOAPPIO_NEXT_DAY": {"price": 30, "active": true}, "VELOAPPIO_SAME_DAY": {"price": 30, "active": true}, "VELOAPPIO_STANDARD": {"price": 30, "active": true}, "VELOAPPIO_ON_DEMAND": {"price": 5, "active": false, "margin": true}, "VELOAPPIO_INTERNATIONAL": {"price": 5, "active": false, "margin": true}, "VELOAPPIO_LOCKER2LOCKER": {"price": "20", "active": false}}]',
                'slug' => 'tzah',
                'suspended' => 0,
                'tax_id' => NULL,
                'timezone' => 'Asia/Jerusalem',
                'updated_at' => '2024-06-20 18:00:05',
                'user_id' => 181,
                'validate_inventory' => 0,
                'validate_weight' => 0,
                'volume' => 0,
                'website' => 'https://tzah.com',
                'week_starts_at' => 7,
                'weekly_deliveries_schedule' => '{"1": {"hours": "12:45", "active": true}, "2": {"hours": "12:45", "active": true}, "3": {"hours": "12:45", "active": true}, "4": {"hours": "12:45", "active": true}, "5": {"hours": "10:45", "active": false}, "6": {"hours": "00:00", "active": false}, "7": {"hours": "12:45", "active": true}}',
            ),
            7 => 
            array (
                'always_show_next_day_options' => 1,
                'billing_limit' => NULL,
                'blocked_at' => NULL,
                'blocked_by' => NULL,
                'courier_id' => NULL,
                'created_at' => '2023-09-24 12:20:34',
                'currency_id' => 2,
                'deleted_at' => NULL,
                'enterprise_billing' => 0,
                'first_name' => 'ofek',
                'id' => 201,
                'imperial_units' => 0,
                'last_name' => 'avrahmi',
                'name' => 'velo qa',
                'phone' => '0522974726',
                'pricing_settings' => '[{"threshold": 0, "VELOAPPIO_DOMESTIC": {"price": 5, "active": false, "margin": true}, "VELOAPPIO_NEXT_DAY": {"price": 30, "active": true}, "VELOAPPIO_SAME_DAY": {"price": 30, "active": true}, "VELOAPPIO_STANDARD": {"price": 30, "active": true}, "VELOAPPIO_ON_DEMAND": {"price": 5, "active": false, "margin": true}, "VELOAPPIO_INTERNATIONAL": {"price": 5, "active": false, "margin": true}, "VELOAPPIO_LOCKER2LOCKER": {"price": "20", "active": false}}]',
                'slug' => 'velo-qa',
                'suspended' => 0,
                'tax_id' => NULL,
                'timezone' => 'Asia/Jerusalem',
                'updated_at' => '2024-06-20 18:00:10',
                'user_id' => 430,
                'validate_inventory' => 0,
                'validate_weight' => 0,
                'volume' => 0,
                'website' => 'https://app.veloapp.io/onboarding/details',
                'week_starts_at' => 7,
                'weekly_deliveries_schedule' => '{"1": {"hours": "12:45", "active": true}, "2": {"hours": "12:45", "active": true}, "3": {"hours": "12:45", "active": true}, "4": {"hours": "12:45", "active": true}, "5": {"hours": "10:45", "active": false}, "6": {"hours": "00:00", "active": false}, "7": {"hours": "12:45", "active": true}}',
            ),
        ));
        
        
    }
}